site_name: Radius Run Manager Documentation
nav:
  - Home: index.md
  - Design:
      - Use Cases:
          - Callibration: use_cases/callibration.md
          - Load Scans: use_cases/load_scans.md
          - Edit Scans: use_cases/edit_scans.md
          - Start Scans: use_cases/start_scans.md
          - Pause Scans: use_cases/pause_scan.md
theme:
  name: material
plugins:
  - search
  - mermaid2
